version: '3.8'

services:
  # Database
  database:
    image: postgres:15-alpine
    container_name: rp-server-db-dev
    environment:
      POSTGRES_DB: rp_server_db
      POSTGRES_USER: rp_user
      POSTGRES_PASSWORD: rp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rp_user -d rp_server_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rp_network

  # Backend API
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: rp-server-backend-dev
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://rp_user:rp_password@database:5432/rp_server_db
      - SECRET_KEY=dev-secret-key-2024
      - DEBUG=true
      - PROJECT_NAME=RP Server Backend Dev
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
    networks:
      - rp_network

  # Frontend Development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: rp-server-frontend-dev
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/package.json:/app/package.json
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - rp_network

volumes:
  postgres_data:

networks:
  rp_network:
    driver: bridge