"""add_city_and_entry_date_to_passport

Revision ID: 39313b81edf6
Revises: 9df145c80914
Create Date: 2025-07-11 13:08:22.123456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39313b81edf6'
down_revision = '9df145c80914'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Добавляем колонки как nullable сначала
    op.add_column('passports', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('passports', sa.Column('city_entry_date', sa.DateTime(timezone=True), nullable=True))

    # 2. Заполняем существующие записи значениями по умолчанию
    # Устанавливаем текущее время для city_entry_date
    op.execute("UPDATE passports SET city = 'Los Santos' WHERE city IS NULL")
    op.execute("UPDATE passports SET city_entry_date = NOW() WHERE city_entry_date IS NULL")

    # 3. Теперь делаем колонки NOT NULL
    op.alter_column('passports', 'city', nullable=False)
    op.alter_column('passports', 'city_entry_date', nullable=False)

    # 4. Создаем индексы
    op.create_index(op.f('ix_passports_city'), 'passports', ['city'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passports_city'), table_name='passports')
    op.drop_column('passports', 'city_entry_date')
    op.drop_column('passports', 'city')
    # ### end Alembic commands ###