"""make_user_id_nullable_in_logs

Revision ID: 26a996733fe0
Revises: b305c08d9155
Create Date: 2025-07-16 15:31:31.104203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26a996733fe0'
down_revision = 'b305c08d9155'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make user_id nullable in logs table for anonymous events
    op.alter_column('logs', 'user_id',
                    existing_type=sa.Integer(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make user_id non-nullable again (rollback)
    op.alter_column('logs', 'user_id',
                    existing_type=sa.Integer(),
                    nullable=False)
    # ### end Alembic commands ###