"""add_discord_id_and_uuid_to_passport

Revision ID: c1e4f8b2a345
Revises: b305c08d9155
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e4f8b2a345'
down_revision = 'b305c08d9155'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем новые поля
    op.add_column('passports', sa.Column('discord_id', sa.String(length=20), nullable=True))
    op.add_column('passports', sa.Column('uuid', sa.String(length=36), nullable=True))
    
    # Создаем индексы
    op.create_index(op.f('ix_passports_discord_id'), 'passports', ['discord_id'], unique=True)
    op.create_index(op.f('ix_passports_uuid'), 'passports', ['uuid'], unique=True)
    
    # Делаем nickname необязательным (nullable=True)
    op.alter_column('passports', 'nickname', 
                   existing_type=sa.String(length=50),
                   nullable=True)
    
    # После миграции данных, делаем discord_id обязательным
    # Это нужно будет сделать отдельно после заполнения данных
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем nickname как обязательное поле
    op.alter_column('passports', 'nickname',
                   existing_type=sa.String(length=50),
                   nullable=False)
    
    # Удаляем индексы
    op.drop_index(op.f('ix_passports_uuid'), table_name='passports')
    op.drop_index(op.f('ix_passports_discord_id'), table_name='passports')
    
    # Удаляем новые колонки
    op.drop_column('passports', 'uuid')
    op.drop_column('passports', 'discord_id')
    # ### end Alembic commands ###