"""make_discord_id_required

Revision ID: d2f5g9c3b456
Revises: c1e4f8b2a345
Create Date: 2025-01-27 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f5g9c3b456'
down_revision = 'c1e4f8b2a345'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Делаем discord_id обязательным после заполнения данных
    op.alter_column('passports', 'discord_id',
                   existing_type=sa.String(length=20),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Делаем discord_id необязательным
    op.alter_column('passports', 'discord_id',
                   existing_type=sa.String(length=20),
                   nullable=True)
    # ### end Alembic commands ###