"""update_passport_model_for_discord_integration

Revision ID: e3g6h9d5c567
Revises: d2f5g9c3b456
Create Date: 2025-01-27 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3g6h9d5c567'
down_revision = 'd2f5g9c3b456'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Этот upgrade проверяет существование необходимых изменений
    # и применяет их если они еще не применены
    
    # Проверяем текущую структуру таблицы
    inspector = sa.inspect(op.get_bind())
    columns = [column['name'] for column in inspector.get_columns('passports')]
    
    # Если discord_id еще не добавлен
    if 'discord_id' not in columns:
        op.add_column('passports', sa.Column('discord_id', sa.String(length=50), nullable=True))
        op.create_index('ix_passports_discord_id', 'passports', ['discord_id'], unique=True)
    
    # Если uuid еще не добавлен
    if 'uuid' not in columns:
        op.add_column('passports', sa.Column('uuid', sa.String(length=50), nullable=True))
        op.create_index('ix_passports_uuid', 'passports', ['uuid'], unique=False)
    
    # Делаем nickname необязательным
    op.alter_column('passports', 'nickname',
                   existing_type=sa.String(length=50),
                   nullable=True)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Возвращаем nickname как обязательное поле
    # ВНИМАНИЕ: Это может привести к ошибкам если есть NULL значения
    op.alter_column('passports', 'nickname',
                   existing_type=sa.String(length=50),
                   nullable=False)
    
    # Удаляем индексы и колонки
    op.drop_index('ix_passports_uuid', table_name='passports')
    op.drop_index('ix_passports_discord_id', table_name='passports')
    op.drop_column('passports', 'uuid')
    op.drop_column('passports', 'discord_id')
    # ### end Alembic commands ###